### ISSUE TITLE
Delegate REV for Staking like Tezos.

### ISSUE THREAD

**Issue by dimworm** [rchain/rchip-proposals#15]
People can delegate their REV to a staking pool. Their REV does not need to leave their wallet. 
Reference: https://medium.com/anonstake/staking-tezos-xtz-how-to-delegate-tezos-with-trustwallet-f3b97e542711

**Comment by 9rb** [comment]
Delegated proof of stake? Discuss with Greg to get more clarity on how this is working and relationship to network security.

**Comment by jimscarver** [comment]
Tezos use your whole wallet for staking because there is no risk of losing any of the balance, only the rewards are slashed.

**Comment by 9rb** [comment]
Greg: Tezos is based on Delegated Proof of Stake which has well known issues. Rchain is not doing this and so this is not applicable to us. Delegation in our situation will cause serious network security issues.  Recommend the issue be closed.
