### ISSUE TITLE
Specify the unit by which Validators may unbond

### ISSUE THREAD

**Issue by SteveHenley** [rchain/rchip-proposals#3]
**Description**
Strategic Category: Reduce Risk - 3

**Background:**
To reduce the risk of 'all' validators abruptly leaving the platform, it is advisable to throttle the rate at which unbonding requests can be processed.  In order to specify a rate, it is necessary to specify what unit the rate will use.  There are 2 options:

- The amount of staked token / count of blocks  OR
- 
- The number of validators / count of blocks

Subtasks are attached.  Please vote on which one should be used.

https://rchain.atlassian.net/browse/RIP-1
Created October 9, 2018, 5:31 PM
[Governance of the Blockchain - Draft](https://rchain.atlassian.net/wiki/spaces/CORE/pages/564035820/Governance+of+the+Blockchain+-+Draft)

**Comment by 9rb** [comment]
Check with Greg

**Comment by 9rb** [comment]
This issue is combined with Issue 3
