### ISSUE TITLE
Staked token / count of blocks

### ISSUE THREAD

**Issue by SteveHenley** [rchain/rchip-proposals#5]
**Description**
None

[https://rchain.atlassian.net/browse/RIP-3?src=confmacro](url)
Created October 9, 2018, 5:38 PM
[Governance of the Blockchain - Draft](https://rchain.atlassian.net/wiki/spaces/CORE/pages/564035820/Governance+of+the+Blockchain+-+Draft)

**Comment by 9rb** [comment]
Does this and the validators/ count of blocks have to do with network security? Check with Greg

**Comment by 9rb** [comment]
Greg: if hardware becomes much faster, we may be able to process many more blocks.. say 100x today .. the stake may not have anything to do that
