### ISSUE TITLE
Validators / count of blocks

### ISSUE THREAD

**Issue by SteveHenley** [rchain/rchip-proposals#6]
**Description**
None

[https://rchain.atlassian.net/browse/RIP-4?src=confmacro](url)
Created October 9, 2018, 5:38 PM
[Governance of the Blockchain - Draft](https://rchain.atlassian.net/wiki/spaces/CORE/pages/564035820/Governance+of+the+Blockchain+-+Draft)

**Comment by 9rb** [comment]
Not clear what this is about..

**Comment by 9rb** [comment]
Greg: This is trying to put a constraint on stake distribution. Let the market decide what configurations may be accepted by which consumers.. Need functionality to display shard characteristics so that the consumers can make informed decisions.
